### ISSUE TITLE
tag a new release

### ISSUE THREAD

**Issue by yasushi-saito** [MaxHalford/eaopt#37]
With go modules, "go get github.com/MaxHalford/eaopt" will fetch v0.1.0, which is very old. Can you tag a new release, say v0.2.0?

**Comment by MaxHalford** [comment]
Sure!

**Comment by yasushi-saito** [comment]
I think the tag must start with "v". From https://github.com/golang/go/wiki/Modules:

Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. If using Git, tag released commits with their versions. Public and private module repositories and proxies are becoming available (see FAQ below).

**Comment by JensRantil** [comment]
@MaxHalford I just discovered this library. It's wonderful! Let me know if you'd like me to get access to correct the version tags. Also, there's been a fair amound of changes since 0.4.1 was published. Might make sense to create anothe release.

**Comment by MaxHalford** [comment]
Hey @JensRantil! Sure that would be nice. I don't write much Go code these days so I'm not aware of the latest best practices.

**Comment by JensRantil** [comment]
@MaxHalford Nice! Let me know when you've given me write permission to this repo and I'll push correct tags. I'll keep the old tags in case anyone's using them.

**Comment by MaxHalford** [comment]
Should be good @JensRantil :)

**Comment by spakin** [comment]
I think this issue can be closed, right?  I see the current eaopt is semantically tagged as v0.4.2.

**Comment by JensRantil** [comment]
Correct. Thanks for reminding me/us!
