### ISSUE TITLE
Is CrossUniformFloat64 correct?

### ISSUE THREAD

**Issue by spakin** [MaxHalford/eaopt#46]
I was just looking at the [source code for CrossUniformFloat64](https://github.com/MaxHalford/eaopt/blob/ba4b9950c779780a53c588b69769a830f58e106a/crossover.go#L15), and I'm a bit puzzled by it.  It assigns p1[i] a proportion of each of the old p1[i] and the old p2[i], but then it assigns p2[i] a proportion of each of the *new* p1[i] and the old p2[i]. Shouldn't it be using some intermediate variables to correctly distribute the parents' values to the children?

**Comment by MaxHalford** [comment]
Hey there @spakin! I don't work on eaopt actively anymore, and I don't have the bandwidth to look into this at the present time. The best thing to do would be to check yourself and/or write some kind of unit test :)

**Comment by spakin** [comment]
@MaxHalford: I checked, and the problem is manifested by CrossUniformFloat64 not preserving the total value from parents to offspring.  In pull request #47, the code first computes the two new values and then assigns them to p1[i] and p2[i].  I correspondingly updated the unit tests to check for the old, bad behavior.

**Comment by MaxHalford** [comment]
Cheers! Nice and sweet PR. It makes me want to give some love back to the library.
