### ISSUE TITLE
Opt into Go module system

### ISSUE THREAD

**Issue by spakin** [MaxHalford/eaopt#48]
Cheers! Nice and sweet PR. It makes me want to give some love back to the library.

_Originally posted by @MaxHalford in https://github.com/MaxHalford/eaopt/issues/46#issuecomment-727143472_

**Comment by spakin** [comment]
Glad to hear it!  I quite like `eaopt` and would like to see it continue to evolve.  (Ha!)

Would you be willing to opt into the Go module system?  The steps are as follows (untested):

```bash
go mod init github.com/MaxHalford/eaopt
git add go.mod go.sum
git commit
git tag v0.4.2
git push
git push --tags
```

**Comment by MaxHalford** [comment]
Yes good idea :)

**Comment by MaxHalford** [comment]
Done!

**Comment by spakin** [comment]
Thanks!  From a quick test, this seems to work.
